spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: true
  url:
    base: http://34.64.39.209:8080
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://34.64.36.79:3306/dev_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: devuser
    password: simple0311
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual

path:
  front_page: http://www.naver.com

hls:
  ffmpeg: C://ProgramData/chocolatey/bin/ffmpeg.exe
  ffprobe: C://ProgramData/chocolatey/bin/ffprobe.exe

server:
  root-path: /home/hansol8701
  media-path: /media

swagger:
  enable: true